name: Deploy Website

on:
  pull_request:
    # Enumeration needed to also remove the preview pages on PR close
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - main
      - agent
  workflow_dispatch:

permissions:
  contents: write # to write to github pages branch
  pull-requests: write # to update comments
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref_name == 'main'
        with:
          folder: ./app
          clean-exclude: pr-preview/
          force: false
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        if: github.event.pull_request
        with:
          source-dir: ./app
          umbrella-dir: pr-preview
          action: auto
