name: Deploy Website 12

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.event.pull_request.number || 'production' }}"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref_name == 'main'
        with:
          folder: ./app
          clean-exclude: pr-preview/
          force: false

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        if: github.event_name == 'pull_request'
        with:
          source-dir: ./app
          umbrella-dir: pr-preview
          action: auto
